#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backing up the original config just in case
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Append the frontend/backend configuration
cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server web-01 13.220.214.222:80 check
    server web-02 44.203.142.57:80 check
EOF

service haproxy restart

exit 0
