#!/usr/bin/env bash
# Installs Nginx and configures a custom 404 page
apt-get -y update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/root \/var\/www\/html;/a \\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default

service nginx restart || service nginx start
